# Отключённые правила
disabled_rules:
  - line_length         # Отключаем проверку длины строки
  - identifier_name     # Игнорируем короткие названия переменных и функций

# Включённые правила
opt_in_rules:
  - closure_spacing     # Проверка пробелов в замыканиях

# Каталоги, которые будут проверяться
included:
  - DayTrack            # Указываем корневую папку проекта

# Каталоги, которые будут исключены из проверки
excluded:
  - Pods                # Исключаем папку Pods


